// Generated by CoffeeScript 1.10.0
(function() {
  var Evernote, Note, RedisNote, Sync2, SyncStatus, Tags, async, client, crypto, express, fs, getLocalTime, getYear, help, isEmpty, noteStore, redis, router, toInt, uniq;

  express = require('express');

  router = express.Router();

  async = require('async');

  uniq = require('uniq');

  fs = require('fs');

  crypto = require('crypto');

  Evernote = require('evernote').Evernote;

  client = require('../servers/ervernote');

  noteStore = client.getNoteStore('https://app.yinxiang.com/shard/s5/notestore');

  Note = require('../models/note');

  Tags = require('../models/tags');

  SyncStatus = require('../models/sync_status');

  redis = require('../models/redis')();

  RedisNote = require('../servers/redis-note');

  Sync2 = require('../servers/sync2');

  help = require('../servers/help');

  getLocalTime = help.getLocalTime;

  getYear = help.getYear;

  toInt = help.toInt;

  isEmpty = help.isEmpty;


  /* GET home page. */

  router.get('/', function(req, res, next) {
    var count, page;
    page = toInt(req.query.page);
    if (page <= 0 || !page) {
      page = 1;
    }
    count = 0;
    return async.parallel({
      getCount: function(cb) {
        return redis.get('noteCount', function(err, number) {
          if (err) {
            return console.log(err);
          }
          count = Math.ceil(number / 10);
          return cb();
        });
      },
      pageNote: function(cb) {
        return redis.get('page:' + page, function(err, notes) {
          if (err) {
            return console.log(err);
          }
          if (isEmpty(notes)) {
            return next();
          }
          notes = JSON.parse(notes);
          return cb(null, notes);
        });
      },
      getRecentNote: function(cb) {
        return redis.get('recentNote', function(err, notes) {
          if (err) {
            return console.loge(err);
          }
          if (isEmpty(notes)) {
            return next();
          }
          notes = JSON.parse(notes);
          return cb(null, notes);
        });
      },
      getTags: function(cb) {
        return redis.hgetall('tags', function(err, tags) {
          if (err) {
            return console.log(err);
          }
          if (isEmpty(tags)) {
            return next();
          }
          tags.tags = tags.tags.split(',');
          return cb(null, tags);
        });
      }
    }, function(err, result) {
      if (err) {
        return console.log(err);
      }
      return res.render('index', {
        notes: result.pageNote,
        currPage: page,
        countPage: count,
        recentNote: result.getRecentNote,
        tags: result.getTags.tags,
        title: "友情's 笔记"
      });
    });
  });


  /* 查找对应笔记 */

  router.get('/note/:noteGuid', function(req, res, next) {
    var noteGuid;
    noteGuid = req.params.noteGuid;
    return async.parallel({
      findNote: function(cb) {
        return redis.hgetall(noteGuid, function(err, notes) {
          if (err) {
            return console.log(err);
          }
          if (isEmpty(notes)) {
            return next();
          }
          notes.tags = notes.tags.split(',');
          return cb(null, notes);
        });
      },
      recentNote: function(cb) {
        return redis.get('recentNote', function(err, notes) {
          if (err) {
            return console.loge(err);
          }
          notes = JSON.parse(notes);
          return cb(null, notes);
        });
      },
      getTags: function(cb) {
        return redis.hgetall('tags', function(err, tags) {
          if (err) {
            return console.log(err);
          }
          tags.tags = tags.tags.split(',');
          return cb(null, tags);
        });
      }
    }, function(autoErr, result) {
      if (autoErr) {
        return console.log(autoErr);
      }
      return res.render('note', {
        note: result.findNote,
        recentNote: result.recentNote,
        tags: result.getTags.tags,
        title: result.findNote.title
      });
    });
  });


  /* 查找对应标签笔记列表 */

  router.get('/tag/:tag/', function(req, res, next) {
    var tag;
    tag = req.params.tag.trim();
    return async.parallel({
      findNotes: function(cb) {
        return Note.find({
          tags: tag
        }, {
          'title': 1,
          'guid': 1,
          'tags': 1,
          'updated': 1,
          'created': 1
        }).sort('-created').exec(function(err, notes) {
          if (err) {
            return console.log(err);
          }
          if (!notes.length) {
            return next();
          }
          return cb(null, notes);
        });
      },
      getTags: function(cb) {
        return Tags.findOne(function(err, tags) {
          if (err) {
            return console.log(err);
          }
          return cb(null, tags);
        });
      }
    }, function(autoErr, result) {
      if (autoErr) {
        return console.log(autoErr);
      }
      return res.render('tags_note', {
        notes: result.findNotes,
        tag: tag,
        getLocalTime: getLocalTime,
        tags: result.getTags.tags,
        title: "Tags " + tag
      });
    });
  });


  /* 档案 */

  router.get('/archive', function(req, res) {
    return async.auto({
      getNotes: function(cb) {
        return Note.find({}, {
          'guid': 1,
          'created': 1,
          'title': 1
        }).sort('-created').exec(function(err, notes) {
          if (err) {
            return console.log(err);
          }
          return cb(null, notes);
        });
      },
      getYear: [
        'getNotes', function(cb, result) {
          var archive, notes;
          notes = result.getNotes;
          archive = {};
          return async.eachSeries(notes, function(item, callback) {
            var year;
            year = getYear(item.created);
            if (!archive[year]) {
              console.log("year ==>", year);
              archive[year] = [];
              archive[year].push(item);
            } else {
              archive[year].push(item);
            }
            return callback();
          }, function(eachErr) {
            if (eachErr) {
              return console.log(eachErr);
            }
            return res.render('archive', {
              archives: archive,
              getLocalTime: getLocalTime,
              title: "Archive List"
            });
          });
        }
      ]
    });
  });

  router.get('/about', function(req, res) {
    return res.render('about', {
      title: 'About'
    });
  });

  router.get('/sync2', function(req, res) {
    var sync;
    sync = new Sync2();
    return async.auto({
      checkStatus: function(cb) {
        return cb();
      },
      syncInfo: [
        'checkStatus', function(cb) {
          return sync.syncInfo(cb);
        }
      ],
      cacheInfo: [
        'syncInfo', function(cb) {
          var rn;
          rn = new RedisNote();
          rn.cacheRedis();
          return res.send("sync ok");
        }
      ]
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
