// Generated by CoffeeScript 1.8.0
(function() {
  var Evernote, client, config, oauthAccessToken;

  config = require('../config.json');

  Evernote = require('evernote').Evernote;

  oauthAccessToken = process.env.oauthAccessToken;

  client = new Evernote.Client({
    token: oauthAccessToken
  });

  module.exports = client;

}).call(this);

//# sourceMappingURL=ervernote.js.map
