// Generated by CoffeeScript 1.10.0
(function() {
  var Evernote, client, config, developerToken;

  config = require('../config.json');

  Evernote = require('evernote').Evernote;

  developerToken = process.env.DeveloperToken;

  client = new Evernote.Client({
    token: developerToken
  });

  module.exports = client;

}).call(this);

//# sourceMappingURL=ervernote.js.map
