// Generated by CoffeeScript 1.10.0
(function() {
  var mongoose, noteSchema, uniq;

  mongoose = require('./mongoose');

  uniq = require('uniq');

  noteSchema = mongoose.Schema({
    guid: {
      type: String,
      unique: true
    },
    title: String,
    content: String,
    created: Number,
    updated: Number,
    deleted: Boolean,
    tagGuids: Array,
    notebookGuid: String,
    htmlContent: String,
    tags: Array
  });

  noteSchema.methods.findSameGuid = function(cb) {
    return this.model('Note').findOne({
      guid: this.guid
    }, cb);
  };

  noteSchema.methods.getAllTagName = function(cb) {
    return this.model('Note').find({}, {
      'tags': 1
    }).exec(function(err, notes) {
      var i, j, len, len1, note, ref, t, tags;
      if (err) {
        return console.log(err);
      }
      tags = [];
      for (i = 0, len = notes.length; i < len; i++) {
        note = notes[i];
        ref = notes.tags;
        for (j = 0, len1 = ref.length; j < len1; j++) {
          t = ref[j];
          tags.push(t);
        }
      }
      return tags = uniq(tags);
    });
  };

  module.exports = mongoose.model('Note', noteSchema);

}).call(this);

//# sourceMappingURL=note.js.map
