// Generated by CoffeeScript 1.8.0
(function() {
  var mongoose, noteSchema, uniq;

  mongoose = require('./mongoose');

  uniq = require('uniq');

  noteSchema = mongoose.Schema({
    guid: String,
    title: String,
    content: String,
    created: Number,
    updated: Number,
    deleted: Boolean,
    tagGuids: Array,
    notebookGuid: String,
    tags: Array
  });

  noteSchema.methods.findSameGuid = function(cb) {
    return this.model('Note').findOne({
      guid: this.guid
    }, cb);
  };

  noteSchema.methods.getAllTagName = function(cb) {
    return this.model('Note').find({}, {
      'tags': 1
    }).exec(function(err, notes) {
      var note, t, tags, _i, _j, _len, _len1, _ref;
      if (err) {
        return console.log(err);
      }
      tags = [];
      for (_i = 0, _len = notes.length; _i < _len; _i++) {
        note = notes[_i];
        _ref = notes.tags;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          t = _ref[_j];
          tags.push(t);
        }
      }
      return tags = uniq(tags);
    });
  };

  module.exports = mongoose.model('Note', noteSchema);

}).call(this);

//# sourceMappingURL=note.js.map
