// Generated by CoffeeScript 1.8.0
(function() {
  var mongoose, noteSchema;

  mongoose = require('./mongoose');

  noteSchema = mongoose.Schema({
    guid: String,
    title: String,
    content: String,
    created: Number,
    updated: Number,
    deleted: Boolean,
    tagGuids: Array,
    notebookGuid: String
  });

  noteSchema.methods.findSameGuid = function(cb) {
    return this.model('Note').findOne({
      guid: this.guid
    }, cb);
  };

  module.exports = mongoose.model('Note', noteSchema);

}).call(this);

//# sourceMappingURL=note.js.map
