// Generated by CoffeeScript 1.10.0
(function() {
  var Redis;

  Redis = require('ioredis');

  module.exports = function() {
    var redis;
    return redis = new Redis();
  };

}).call(this);

//# sourceMappingURL=redis.js.map
