// Generated by CoffeeScript 1.8.0
(function() {
  var mongoose, syncInfoSchema;

  mongoose = require('./mongoose');

  syncInfoSchema = mongoose.Schema({
    syncStatus: Number
  });

  module.exports = mongoose.model('syncInfo', syncInfoSchema);

}).call(this);

//# sourceMappingURL=sync_info.js.map
