// Generated by CoffeeScript 1.8.0
(function() {
  var mongoose, statusSchema;

  mongoose = require('./mongoose');

  statusSchema = mongoose.Schema({
    currentTime: Number,
    fullSyncBefore: Number,
    updateCount: Number,
    uploaded: Number
  });

  module.exports = mongoose.model('SyncStatus', statusSchema);

}).call(this);

//# sourceMappingURL=sync_status.js.map
